//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JrBase.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JrBase.Languages.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Select Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tool_Recipe {
            get {
                return ResourceManager.GetString("tool_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCEL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Cancel {
            get {
                return ResourceManager.GetString("wrd_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXIT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Exit {
            get {
                return ResourceManager.GetString("wrd_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_IO {
            get {
                return ResourceManager.GetString("wrd_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Log {
            get {
                return ResourceManager.GetString("wrd_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Main {
            get {
                return ResourceManager.GetString("wrd_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MANUAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Manual {
            get {
                return ResourceManager.GetString("wrd_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_No {
            get {
                return ResourceManager.GetString("wrd_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Ok {
            get {
                return ResourceManager.GetString("wrd_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAUSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Pause {
            get {
                return ResourceManager.GetString("wrd_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RECIPE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Recipe {
            get {
                return ResourceManager.GetString("wrd_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Reset {
            get {
                return ResourceManager.GetString("wrd_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETUP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Setup {
            get {
                return ResourceManager.GetString("wrd_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Start {
            get {
                return ResourceManager.GetString("wrd_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Stop {
            get {
                return ResourceManager.GetString("wrd_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEACH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Teach {
            get {
                return ResourceManager.GetString("wrd_Teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YES과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string wrd_Yes {
            get {
                return ResourceManager.GetString("wrd_Yes", resourceCulture);
            }
        }
    }
}
